target-version = "py312"

respect-gitignore = true
force-exclude = true
line-length = 120
indent-width = 4

extend-exclude = []

[lint]
preview = false
explicit-preview-rules = true

select = ["ALL"]
fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
task-tags = ["TODO", "FIXME", "XXX", "HACK", "BUG", "NOTE"]

ignore = [
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "D203",
    "D213",
    "E501",
]

[lint.per-file-ignores]
"tests/**" = ["S101", "D", "ANN"]
"**/__init__.py" = ["F401"]

[lint.pycodestyle]
max-doc-length = 120
ignore-overlong-task-comments = true

[lint.pydocstyle]
convention = "google"
ignore-var-parameters = true

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = true
known-first-party = []

[lint.mccabe]
max-complexity = 12

[lint.pylint]
max-args = 8
max-branches = 12
max-returns = 6
max-statements = 50
max-bool-expr = 5

[lint.flake8-annotations]
ignore-fully-untyped = false
mypy-init-return = true
suppress-dummy-args = true
suppress-none-returning = true

[lint.flake8-bandit]
check-typed-exception = true

[lint.flake8-builtins]
strict-checking = true
